spring:
  application:
    name: flower-subscription-backend

  # Временно отключаем автоконфигурацию базы данных.
  # Удалим этот блок на втором этапе,
  # когда подключим PostgreSQL и Flyway.
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html

info:
  application:
    name: ${spring.application.name}
    description: Backend REST API for a flower shop subscription service